//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZuydRPG_EF.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Characters = new HashSet<Character>();
            this.Monsters = new HashSet<Monster>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Monster> Monsters { get; set; }
    }
}
