//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZuydRPG_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gear
    {
        public int Id { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
